blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.groupez.dev/
    about: My personal Discord server
  - name: Spigot page
    url: https://www.spigotmc.org/resources/authors/maxlego08.276655/
    about: Official SpigotMC.org page of GroupeZ